// Code generated by: bella secrets generate go
// Project: my-project/production/vault
// Generated: 2025-01-15 10:30:00 UTC
// DO NOT edit manually — re-run bella secrets generate go to update.
package secrets

import (
"encoding/json"
"fmt"
"net/url"
"os"
"strconv"
"strings"

"github.com/google/uuid"
)

type AppConfigShape struct {
	Setting1 string `json:"setting1"`
	Setting2 int    `json:"setting2"`
}

type AppSecrets struct{}

func mustGetenv(key string) string {
v := os.Getenv(key)
if v == "" {
panic(fmt.Sprintf("Required environment variable '%s' is not set.", key))
}
return v
}

// ExternalApiKey returns the third-party API key (String).
func (s AppSecrets) ExternalApiKey() string { return mustGetenv("EXTERNAL_API_KEY") }

// Port returns the HTTP server port (Int).
func (s AppSecrets) Port() int { v, _ := strconv.Atoi(mustGetenv("PORT")); return v }

// EnableFeatures returns the feature toggle (Bool).
func (s AppSecrets) EnableFeatures() bool { return mustGetenv("ENABLE_FEATURES") == "true" }

// DatabaseUrl returns the PostgreSQL connection string (Uri).
func (s AppSecrets) DatabaseUrl() *url.URL {
raw := mustGetenv("DATABASE_URL")
u, err := url.Parse(raw)
if err != nil || u == nil {
// Demo URLs may have non-numeric ports; extract scheme manually.
u = &url.URL{}
if i := strings.Index(raw, "://"); i > 0 {
u.Scheme = raw[:i]
}
}
return u
}

// AppConfig returns the application configuration parsed from JSON.
func (s AppSecrets) AppConfig() AppConfigShape {
var cfg AppConfigShape
_ = json.Unmarshal([]byte(mustGetenv("APP_CONFIG")), &cfg)
return cfg
}

// AppId returns the application instance ID (GUID).
func (s AppSecrets) AppId() uuid.UUID {
id, _ := uuid.Parse(mustGetenv("APP_ID"))
return id
}
